sudo: required
language: node_js
node_js:
- '6'
install:
- npm install -g create-elm-app
before_script:
- elm-app package install -y
script:
- elm-app build
after_success:
- echo Done!
deploy:
  provider: s3
  access_key_id: AKIAJRT3QZUDENHSRSVA
  secret_access_key:
    secure: apgMpN7HQuJMgx8FLmtWgZp9n61HpTd5+aBqySiqUZdFNSj1fDcY3MY1Bs6C/6V150JVJDYxXtyHPHvA3SxyEL6gksBcFHeBYp/Fj1434QEuYH+dZU8Supwwj1J0jmPbAU5+BQMVhArPQFyprGKcUn3kz6vBtjbAP4LkDHOb05AAWL1j+0aK6oRwd1k4gxRh/dxbIU0JfsIO3lvCtDmI8Lpjm0evAWS8p0JP8K4Fd8Oqj4xv8KPyP3RPDz0EubbAYTHlTyaVxh9ZzlBDlXSyN0PiZaOz1cS8cp6ogOc4BJHOGlT/Q4fgr4RivJcdSTg2UsnwC3Rdm4JfzRaSqwrI3XCRXwbZ0cLf2wS0Y0ow3JAk5psGqh0Ft7Jp0P+JDDMjEhNk9ZmWIZ6sYPRq3Xbh0u/fz4Jrkq6SZBUwCZHDtSBexZ+gtNZVxsN9mKwkGN/glIVEWHJXr7qSAb9e/uB+DdFRqEKdG+Hce2yVkPGN+foeuZ5qU7moqAdOXn/IbwfM4d6r/2SOXvUTlC2r9S3jkSMMZ2yZF39ogupC/X7eiVawitMtyKFCEQoo0uQ5on1+NjZh0G4ITwaOZ8uh+Uws1GxvJeNPleiNk+Spl402Z/E3N0AX+nbfRtB5245qfzRoJpt2f1cmoMFJTvVtTqr7xdxAMOpFjq0GCU9U6IzwkHo=
  bucket: optimize-me
  acl: public_read
  on:
    repo: yannick-cw/optimize-me
  local_dir: build
  skip_cleanup: true
